server:
  port: 8010
  max-http-header-size: 1048576
  tomcat: 
    max-http-post-size: 1048576
spring:
  application:
    name: aigou-common-dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:org/hedee/aigou/mapper/*Mapper.xml
  type-aliases-package: org.hedee.aigou.domain,org.hedee.aigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true